import type { Runner } from "@models/runner.ts";
import { parseIofXmlSplitTimesFile } from "@parsers/iof-xml-parser.ts";
import { expect } from "@std/expect";
import { DOMParser } from "linkedom";
import { IOF_XML_2_SPLIT_TIMES_BIS } from "./mocks/iof-xml-2-split-times-bis.ts";
import { IOF_XML_2_SPLIT_TIMES } from "./mocks/iof-xml-2-split-times.ts";
import { IOF_XML_3_SPLIT_TIMES } from "./mocks/iof-xml-3-split-times.ts";

Deno.test("parseIofXmlSplitTimesFile()", (t) => {
  const parser = new DOMParser();

  t.step("Iof XML 2 file", () => {
    const xmlLinkeDomDoc2 = parser.parseFromString(
      IOF_XML_2_SPLIT_TIMES,
      "text/xml"
    );
    // @ts-ignore
    const xmlDoc2 = xmlLinkeDomDoc2 as XMLDocument;

    const [runners, splitsError] = parseIofXmlSplitTimesFile(
      xmlDoc2,
      "Dames",
      "+02:00",
      "2022-03-11"
    );

    const firstRunner = runners?.at(0);
    if (firstRunner) firstRunner.id = "1";

    t.step("expecte first runner to be strict equal.", () => {
      expect(firstRunner).toStrictEqual(expectedOk2);
    });

    // console.log(inspect(runners?.at(0), { depth: null }), splitsError);
  });

  t.step("Another Iof XML 2 file", () => {
    const xmlLinkeDomDoc2 = parser.parseFromString(
      IOF_XML_2_SPLIT_TIMES_BIS,
      "text/xml"
    );
    // @ts-ignore
    const xmlDoc2 = xmlLinkeDomDoc2 as XMLDocument;

    const [runners, splitsError] = parseIofXmlSplitTimesFile(
      xmlDoc2,
      "Hommes",
      "+02:00",
      "2022-03-11"
    );

    const firstRunner = runners?.at(0);
    if (firstRunner) firstRunner.id = "1";
  });

  t.step("Iof XML 3 file", () => {
    const xmlLinkeDomDoc3 = parser.parseFromString(
      IOF_XML_3_SPLIT_TIMES,
      "text/xml"
    );
    // @ts-ignore
    const xmlDoc3 = xmlLinkeDomDoc3 as XMLDocument;
    const [runners, runnersError] = parseIofXmlSplitTimesFile(
      xmlDoc3,
      "1",
      "+02:00",
      "2022-03-11"
    );

    const firstRunner = runners?.at(0);
    if (firstRunner) firstRunner.id = "1";

    const lastRunner = runners?.at(-1);
    if (lastRunner) lastRunner.id = "48";

    t.step("expecte first runner to be strict equal.", () => {
      expect(firstRunner).toStrictEqual(expectedOK3);
    });

    t.step(
      "expecte last runner with missing controls to be strict equal.",
      () => {
        expect(lastRunner).toStrictEqual(expectedNotOK3);
      }
    );
  });
});

const expectedOk2 = {
  id: "1",
  userId: null,
  trackingDeviceId: null,
  status: "ok",
  firstName: "Annabelle",
  lastName: "DELENNE",
  startTime: 1647015397,
  time: 959,
  legs: [
    {
      startControlCode: "start",
      finishControlCode: "31",
      timeOverall: 55,
      time: 55,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "31",
      finishControlCode: "32",
      timeOverall: 136,
      time: 81,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "32",
      finishControlCode: "33",
      timeOverall: 290,
      time: 154,
      rankSplit: 2,
      timeBehindSplit: 4,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 4,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "33",
      finishControlCode: "34",
      timeOverall: 341,
      time: 51,
      rankSplit: 2,
      timeBehindSplit: 1,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 5,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "34",
      finishControlCode: "37",
      timeOverall: 428,
      time: 87,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 5,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "37",
      finishControlCode: "38",
      timeOverall: 526,
      time: 98,
      rankSplit: 2,
      timeBehindSplit: 1,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 6,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "38",
      finishControlCode: "39",
      timeOverall: 595,
      time: 69,
      rankSplit: 2,
      timeBehindSplit: 2,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 8,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "39",
      finishControlCode: "40",
      timeOverall: 626,
      time: 31,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 8,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "40",
      finishControlCode: "41",
      timeOverall: 661,
      time: 35,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 8,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "41",
      finishControlCode: "42",
      timeOverall: 716,
      time: 55,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 8,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "42",
      finishControlCode: "43",
      timeOverall: 739,
      time: 23,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 8,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "43",
      finishControlCode: "44",
      timeOverall: 853,
      time: 114,
      rankSplit: 3,
      timeBehindSplit: 5,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 13,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "44",
      finishControlCode: "45",
      timeOverall: 930,
      time: 77,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 13,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "45",
      finishControlCode: "46",
      timeOverall: 949,
      time: 19,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 13,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "46",
      finishControlCode: "3",
      timeOverall: 959,
      time: 10,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 13,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "3",
      finishControlCode: "finish",
      timeOverall: 959,
      time: 0,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 13,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
  ],
  rank: 1,
  timeBehind: 0,
  totalTimeLost: 0,
  track: null,
  timeOffset: 0,
};

const expectedNotOK3: Runner = {
  id: "48",
  trackingDeviceId: null,
  userId: null,
  status: "not-ok",
  firstName: "Angus",
  lastName: "Haines",
  startTime: 1659525360,
  time: null,
  timeOffset: 0,
  legs: [
    {
      startControlCode: "start",
      finishControlCode: "101",
      timeOverall: 123,
      time: 123,
      rankSplit: 37,
      timeBehindSplit: 52,
      rankOverall: 37,
      timeBehindOverall: 52,
      timeBehindSuperman: 52,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "101",
      finishControlCode: "105",
      timeOverall: 798,
      time: 675,
      rankSplit: 48,
      timeBehindSplit: 535,
      rankOverall: 48,
      timeBehindOverall: 576,
      timeBehindSuperman: 587,
      isMistake: true,
      timeLoss: 471,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "105",
      finishControlCode: "107",
      timeOverall: 1489,
      time: 691,
      rankSplit: 46,
      timeBehindSplit: 482,
      rankOverall: 47,
      timeBehindOverall: 1053,
      timeBehindSuperman: 1069,
      isMistake: true,
      timeLoss: 386,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "107",
      finishControlCode: "109",
      timeOverall: 1553,
      time: 64,
      rankSplit: 39,
      timeBehindSplit: 20,
      rankOverall: 47,
      timeBehindOverall: 1071,
      timeBehindSuperman: 1089,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "109",
      finishControlCode: "110",
      timeOverall: 1682,
      time: 129,
      rankSplit: 23,
      timeBehindSplit: 25,
      rankOverall: 47,
      timeBehindOverall: 1075,
      timeBehindSuperman: 1114,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    null,
    null,
    {
      startControlCode: "115",
      finishControlCode: "116",
      timeOverall: 2044,
      time: 59,
      rankSplit: 29,
      timeBehindSplit: 14,
      rankOverall: 45,
      timeBehindOverall: 1104,
      timeBehindSuperman: 1160,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "116",
      finishControlCode: "118",
      timeOverall: 2343,
      time: 299,
      rankSplit: 40,
      timeBehindSplit: 93,
      rankOverall: 45,
      timeBehindOverall: 1197,
      timeBehindSuperman: 1253,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "118",
      finishControlCode: "121",
      timeOverall: 2448,
      time: 105,
      rankSplit: 40,
      timeBehindSplit: 35,
      rankOverall: 45,
      timeBehindOverall: 1231,
      timeBehindSuperman: 1288,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "121",
      finishControlCode: "123",
      timeOverall: 2538,
      time: 90,
      rankSplit: 41,
      timeBehindSplit: 36,
      rankOverall: 42,
      timeBehindOverall: 1224,
      timeBehindSuperman: 1324,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "123",
      finishControlCode: "125",
      timeOverall: 2723,
      time: 185,
      rankSplit: 32,
      timeBehindSplit: 49,
      rankOverall: 42,
      timeBehindOverall: 1255,
      timeBehindSuperman: 1373,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "125",
      finishControlCode: "127",
      timeOverall: 2825,
      time: 102,
      rankSplit: 9,
      timeBehindSplit: 18,
      rankOverall: 42,
      timeBehindOverall: 1327,
      timeBehindSuperman: 1391,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "127",
      finishControlCode: "130",
      timeOverall: 3078,
      time: 253,
      rankSplit: 46,
      timeBehindSplit: 136,
      rankOverall: 44,
      timeBehindOverall: 1453,
      timeBehindSuperman: 1527,
      isMistake: true,
      timeLoss: 82,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "130",
      finishControlCode: "100",
      timeOverall: 3152,
      time: 74,
      rankSplit: 44,
      timeBehindSplit: 29,
      rankOverall: 44,
      timeBehindOverall: 1480,
      timeBehindSuperman: 1556,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    null,
  ],
  rank: null,
  timeBehind: null,
  totalTimeLost: 0,
  track: null,
};

const expectedOK3: Runner = {
  id: "1",
  trackingDeviceId: null,
  userId: null,
  status: "ok",
  firstName: "Miika",
  lastName: "Kirmula",
  startTime: 1659529800,
  time: 1765,
  timeOffset: 0,
  legs: [
    {
      startControlCode: "start",
      finishControlCode: "101",
      timeOverall: 74,
      time: 74,
      rankSplit: 2,
      timeBehindSplit: 3,
      rankOverall: 2,
      timeBehindOverall: 3,
      timeBehindSuperman: 3,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "101",
      finishControlCode: "105",
      timeOverall: 222,
      time: 148,
      rankSplit: 6,
      timeBehindSplit: 8,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 11,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "105",
      finishControlCode: "107",
      timeOverall: 475,
      time: 253,
      rankSplit: 17,
      timeBehindSplit: 44,
      rankOverall: 6,
      timeBehindOverall: 39,
      timeBehindSuperman: 55,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "107",
      finishControlCode: "109",
      timeOverall: 523,
      time: 48,
      rankSplit: 7,
      timeBehindSplit: 4,
      rankOverall: 5,
      timeBehindOverall: 41,
      timeBehindSuperman: 59,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "109",
      finishControlCode: "110",
      timeOverall: 676,
      time: 153,
      rankSplit: 39,
      timeBehindSplit: 49,
      rankOverall: 11,
      timeBehindOverall: 69,
      timeBehindSuperman: 108,
      isMistake: true,
      timeLoss: 42,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "110",
      finishControlCode: "113",
      timeOverall: 751,
      time: 75,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 8,
      timeBehindOverall: 63,
      timeBehindSuperman: 108,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "113",
      finishControlCode: "115",
      timeOverall: 948,
      time: 197,
      rankSplit: 3,
      timeBehindSplit: 1,
      rankOverall: 4,
      timeBehindOverall: 54,
      timeBehindSuperman: 109,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "115",
      finishControlCode: "116",
      timeOverall: 998,
      time: 50,
      rankSplit: 9,
      timeBehindSplit: 5,
      rankOverall: 4,
      timeBehindOverall: 58,
      timeBehindSuperman: 114,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "116",
      finishControlCode: "118",
      timeOverall: 1208,
      time: 210,
      rankSplit: 3,
      timeBehindSplit: 4,
      rankOverall: 4,
      timeBehindOverall: 62,
      timeBehindSuperman: 118,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "118",
      finishControlCode: "121",
      timeOverall: 1288,
      time: 80,
      rankSplit: 12,
      timeBehindSplit: 10,
      rankOverall: 4,
      timeBehindOverall: 71,
      timeBehindSuperman: 128,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "121",
      finishControlCode: "123",
      timeOverall: 1342,
      time: 54,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 3,
      timeBehindOverall: 28,
      timeBehindSuperman: 128,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "123",
      finishControlCode: "125",
      timeOverall: 1479,
      time: 137,
      rankSplit: 2,
      timeBehindSplit: 1,
      rankOverall: 3,
      timeBehindOverall: 11,
      timeBehindSuperman: 129,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "125",
      finishControlCode: "127",
      timeOverall: 1579,
      time: 100,
      rankSplit: 6,
      timeBehindSplit: 16,
      rankOverall: 3,
      timeBehindOverall: 81,
      timeBehindSuperman: 145,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "127",
      finishControlCode: "130",
      timeOverall: 1696,
      time: 117,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 2,
      timeBehindOverall: 71,
      timeBehindSuperman: 145,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "130",
      finishControlCode: "100",
      timeOverall: 1741,
      time: 45,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 2,
      timeBehindOverall: 69,
      timeBehindSuperman: 145,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "100",
      finishControlCode: "finish",
      timeOverall: 1765,
      time: 24,
      rankSplit: 21,
      timeBehindSplit: 4,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 149,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
  ],
  rank: 1,
  timeBehind: 0,
  totalTimeLost: 0,
  track: null,
};
